# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bde1828e763c0da5c74c7de4b96ef97ef132db36c7da6a1621c0a6606358e4af9bb4217047a39145cbf6a6670962a80b179e2feddfa7383866b41671e265aa19

test:
  secret_key_base: 9b3557cf6853b6b55b631f71350f85c761436f8189d4a59a5ce0bd9eadd58491addcdc13e062ea210275d5fdbf41faf9dd4a02869e4d3acc01a67f0ea6df1e36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
